### ISSUE TITLE
More scalable connected components implementation

### ISSUE THREAD

**Issue by jkbradley** [graphframes/graphframes#117]
There have been many reports of the connected components algorithm in GraphX and GraphFrames not scaling.  @mengxr has a prototype of a better algorithm.  This issue is for tracking adding it to GraphFrames master.

Subtasks:
- [x] Implementation: #119
- [x] Improved unit tests: #121
- [x] GraphX legacy support: #122
- [x] Python API: #123
- [x] (optional) checkpoint interval param: #124
- [x] handle skewness in assigning long IDs

**Comment by nchammas** [comment]
Just curious: Is this related at all to the issue described in #116?

**Comment by jkbradley** [comment]
I'm pretty sure not.

**Comment by jkbradley** [comment]
https://github.com/graphframes/graphframes/pull/119

**Comment by mengxr** [comment]
Added one more TODO to handle skewness in assigning long IDs. Otherwise, CC might fail at the first step on skewed graphs.
